version: "3.4"
services:
  altabotui:
    depends_on:
      - altabotservice
    build:
      context: uiv2/
    image: stream-trivia/ui
    ports:
      - "8080:80"

  altabotservice:
    build:
      context: dotnet-api/
    image: stream-trivia/dotnet-api
    ports:
      - "5000:80"
